### ISSUE TITLE
쇼핑 목록 리스트에 Realm Database 구현하기

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#109]
## 📍 Issue

쇼핑 목록 리스트에 Realm Database 구현하기

## ✅ To-do

- [x] SceneDelegate 시작 화면 변경하기
- [x] Realm Database 추가
- [x] 데이터 저장
- [x] 데이터 로드
- [x] 데이터 바인딩
- [x] 데이터 삭제
- [x] 데이터 업데이트(체크, 즐겨찾기 반영)
- [x] UIMenu + Realm 정렬/필터 기능 구현

`220824`
- [x] DataBaseManager 싱글톤 클래스 생성 + 코드 수정
- [x] FileManager 이용해서 Document에 사진 저장, 조회, 삭제 구현

**Comment by Taehyeon-Kim** [comment]
업데이트 할 때 코드가 상당히 난잡하다... 수정이 시급하다.
