### ISSUE TITLE
영진원 일간박스오피스에 Realm Database 구현하기

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#110]
## 📍 Issue

영진원 일간박스오피스에 Realm Database 구현하기

## ✅ To-do

- [x] Realm Database 구축
- [x] 사용자가 처음 앱 실행 했을 때만 API 콜
- [x] 그 이후에는 Realm에서 데이터 꺼내오기
