### ISSUE TITLE
Movie 앱 SignUp UI 구현하기

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#13]
## 📍 Issue

Movie 앱 SignUp UI 구현하기

## ✅ To-do

- [x] SignUpViewController 생성 및 연결
- [x] 회원가입 레이아웃 구현
- [x] UILabel 속성 지정
- [x] UITextField 속성 지정
- [x] UIButton 속성 지정
- [x] UISwitch 속성 지정
- [x] 키보드 내리기 구현
