### ISSUE TITLE
newlyCoinedWord 프로젝트

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#20]
## 📍 Issue

newlyCoinedWord 프로젝트

## ✅ To-do

- [x] 프로젝트 셋업(iOS Version, Device Orientation)
- [x] AppIcon 적용
- [x] Launch Screen 적용
- [x] Main Screen UI 및 Constraints 설정
- [x] Outlet 연결 및 속성 설정
- [x] Tap Gesture
- [x] Search Action
