### ISSUE TITLE
Delivery 앱 네비게이션 컨트롤러 및 탭 바 컨트롤러 구성

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#34]
## 📍 Issue

Delivery 앱 네비게이션 컨트롤러 및 탭 바 컨트롤러 구성

## ✅ To-do

- [x] 메인 화면 UI 디테일 
- [x] 네비게이션 컨트롤러 연결
- [x] 탭 바 컨트롤러 연결
- [x] Appearance 속성 확인
