### ISSUE TITLE
TableViewController 구현 과제, 설정 화면 구현하기

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#57]
## 📍 Issue

TableViewController 구현 과제, 설정 화면 구현하기

<img width="550" alt="스크린샷 2022-07-18 오후 7 27 56" src="https://user-images.githubusercontent.com/61109660/179493218-f054c633-06e7-41a6-856c-12c37b169406.png">

## ✅ To-do

- [x] SeSACWeek3 프로젝트 생성 및 해당 부분에 구현
- [x] case 1. 스토리보드만 이용해서 구현
- [x] case 2. Dynamic Prototypes, 코드로 구현
