### ISSUE TITLE
피드백 정리

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#58]
## 📍 Issue

피드백 정리

## ✅ To-do

- [ ] final 키워드
- [ ] dynamic dispatch / static dispatch
- [ ] Swift WMO
- [ ] forEach vs for-in
- [ ] UserDefaults 키 관리
- [ ] Swift Attribute, Property Wrapper
