### ISSUE TITLE
Library 앱(도서 앱) 화면 전환 구현

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#67]
## 📍 Issue

Library 앱(도서 앱) 화면 전환 구현

![스크린샷 2022-07-21 오전 11 55 17](https://user-images.githubusercontent.com/61109660/180120109-48a0353c-d848-47e5-8a6e-bc6ea19f7ffa.png)

## ✅ To-do

- [x] 네비게이션 바에 검색 버튼 추가
- [x] 검색 화면으로 화면 전환
- [x] 상세 화면으로 화면 전환
- [x] 상세 화면에서 웹 화면으로 화면 전환
