### ISSUE TITLE
Movie, Food Assets 추가

### ISSUE THREAD

**Issue by Taehyeon-Kim** [Taehyeon-Kim/SeSAC#9]
## 📍 Issue

영화 앱, 배달 앱에 필요한 에셋을 추가합니다. (새싹 제공 default assets)

## ✅ To-do

- [x] 루트 디렉터리에 Resources 폴더 생성
- [x] Movie(Netflix) App에 Assets 추가
- [x] Food(Baemin) App에 Assets 추가
